quarkus.datasource.db-kind=oracle
quarkus.datasource.jdbc.url=jdbc:oracle:thin:@oracle.fiap.com.br:1521:orcl
quarkus.datasource.username=rm562822
quarkus.datasource.password=130997
quarkus.hibernate-orm.database.generation=update
quarkus.http.port=8080
quarkus.resteasy-reactive.json.pretty=true