-- ============================
-- T_HC_PACIENTE
-- ============================
INSERT INTO T_HC_PACIENTE
(ID_PACIENTE, NM_PACIENTE, NR_CPF, NR_RG, NR_ALTURA, NR_PESO, DT_NASCIMENTO, DS_ESCOLARIDADE, DS_ESTADO_CIVIL, DS_DESCRICAO)
VALUES (SQ_T_HC_PACIENTE.NEXTVAL, 'Maria Oliveira', '12345678901', '1234567', 1.68, 62.5, TO_DATE('1995-05-10', 'YYYY-MM-DD'), 'Ensino Superior', 'Solteira', 'Paciente com histórico de ansiedade leve');

INSERT INTO T_HC_PACIENTE
(ID_PACIENTE, NM_PACIENTE, NR_CPF, NR_RG, NR_ALTURA, NR_PESO, DT_NASCIMENTO, DS_ESCOLARIDADE, DS_ESTADO_CIVIL, DS_DESCRICAO)
VALUES (SQ_T_HC_PACIENTE.NEXTVAL, 'João da Silva', '23456789012', '2233445', 1.80, 85.2, TO_DATE('1988-03-22', 'YYYY-MM-DD'), 'Ensino Médio', 'Casado', 'Paciente hipertenso sob controle.');

INSERT INTO T_HC_PACIENTE
(ID_PACIENTE, NM_PACIENTE, NR_CPF, NR_RG, NR_ALTURA, NR_PESO, DT_NASCIMENTO, DS_ESCOLARIDADE, DS_ESTADO_CIVIL, DS_DESCRICAO)
VALUES (SQ_T_HC_PACIENTE.NEXTVAL, 'Ana Souza', '34567890123', '3344556', 1.60, 55.0, TO_DATE('1999-09-09', 'YYYY-MM-DD'), 'Ensino Superior', 'Solteira', 'Paciente em acompanhamento psicológico.');

-- ============================
-- T_HC_MEDICO
-- ============================
INSERT INTO T_HC_MEDICO (ID_MEDICO, NM_MEDICO, NR_CRM)
VALUES (SQ_T_HC_MEDICO.NEXTVAL, 'Dr. Lucas Almeida', 'CRM-SP12345');

INSERT INTO T_HC_MEDICO (ID_MEDICO, NM_MEDICO, NR_CRM)
VALUES (SQ_T_HC_MEDICO.NEXTVAL, 'Dra. Fernanda Costa', 'CRM-SP67890');

INSERT INTO T_HC_MEDICO (ID_MEDICO, NM_MEDICO, NR_CRM)
VALUES (SQ_T_HC_MEDICO.NEXTVAL, 'Dr. Rafael Gomes', 'CRM-SP11223');

-- ============================
-- T_HC_CONSULTA
-- ============================
INSERT INTO T_HC_CONSULTA (ID_CONSULTA, DT_HR_CONSULTA, DS_MODALIDADE)
VALUES (SQ_T_HC_CONSULTA.NEXTVAL, TO_DATE('2025-11-06 15:00:00', 'YYYY-MM-DD HH24:MI:SS'), 'Presencial');

INSERT INTO T_HC_CONSULTA (ID_CONSULTA, DT_HR_CONSULTA, DS_MODALIDADE)
VALUES (SQ_T_HC_CONSULTA.NEXTVAL, TO_DATE('2025-11-07 10:00:00', 'YYYY-MM-DD HH24:MI:SS'), 'Online');

INSERT INTO T_HC_CONSULTA (ID_CONSULTA, DT_HR_CONSULTA, DS_MODALIDADE)
VALUES (SQ_T_HC_CONSULTA.NEXTVAL, TO_DATE('2025-11-08 09:30:00', 'YYYY-MM-DD HH24:MI:SS'), 'Presencial');
